# @package _global_
defaults:
  - train.yaml
  - _self_
  - analysis: tokenization
  - visualization: viz_causal
  - override dataset: waymo_analysis.yaml

# General Parameters
task_name: 'analysis' # Reference task name
palette: gist_ncar # Color palette
num_batches: null # Number of batches to load for the analysis experiment. If 'null', it loads all batches.
num_scenarios: null # Number of scenarios to consider for analysis experiment. If 'null', it loads all scenarios
select_mode: true # If 'true' selects mode for visualization
seed: 42 # Seed for random generators

output_path: ./out

split: train # Specify split to consider 'train', 'val' or 'test'
scenarios_path: ${paths.base_path}/processed/mini_causal/training # Specify path to input scenarios

# split: test # Specify split to consider 'train', 'val' or 'test'
# scenarios_path: ${paths.base_path}/processed/mini_causal/testing # Specify path to input scenarios

# Specify name of experiment to consider
experiment_dirs: [
  #  Safe-ST Model (ckpt: epoch_139.ckpt)
  causal-benchmark-labeled_safe-scenetokens_safe-weight_2026-01-13_18-45-53,

  # Causal-ST Model
  # causal-benchmark-labeled_causal-scenetokens_2026-02-05_15-05-18,

  # Student Model
  causal-benchmark-labeled_scenetokens_2026-02-13_19-21-01
]
