# @package _global_
seed: 42 # Seed for random generators
show_run_id: false
models_to_compare: [
  'scenetransformer',
  'wayformer',
  'safe-scenetokens',
  'scenetokens-student',
  'scenetokens-teacher-unmasked'
]

trajectory_forecasting_metrics: [
  'brierFDE',
  'minFDE6',
  'minADE6',
  'missRate',
]

causal_metrics: [
  'causalTP',
  'causalTN',
  'causalFP',
  'causalFN',
  'f1Score',
  'precision',
  'recall',
]

other_metrics: [
  'Runtime',
]

# Benchmark analysis settings
benchmark: null
benchmark_filepath: null
benchmark_colormap: null
benchmark_splits_to_compare: []

# Ego-safeshift analysis
run_ego_safeshift_analysis: false
ego_safeshift_benchmark: 'ego-safeshift-causal-benchmark'
ego_safeshift_filepath: "./meta/runs/ego-safeshift_benchmark.csv"
ego_safeshift_colormap: colorblind
ego_safeshift_splits_to_compare: [
  'test/waymo-causal-ego-safeshift-id',
  'test/waymo-causal-ego-safeshift-ood',
]

# Causal benchmark analysis
run_causal_benchmark_analysis: false
causal_benchmark: 'causal-benchmark-labeled'
causal_benchmark_filepath: "./meta/runs/causal_benchmark.csv"
causal_benchmark_colormap: colorblind
causal_benchmark_splits_to_compare: [
  'test/waymo-mini-causal-testing',
  'test/waymo-remove-noncausal-testing',
]
